<?php

return array(
  array( 'value' => 'none',              'label' => __( 'None', $td ) ),
  array( 'value' => 'jello',             'label' => __( 'Jello', $td ) ),
  array( 'value' => 'pulse',             'label' => __( 'Pulse', $td ) ),
  array( 'value' => 'rubberBand',        'label' => __( 'Rubber Band', $td ) ),
  array( 'value' => 'swing',             'label' => __( 'Swing', $td ) ),
  array( 'value' => 'tada',              'label' => __( 'Tada', $td ) ),
  array( 'value' => 'wobble',            'label' => __( 'Wobble', $td ) ),
  array( 'value' => 'flip',              'label' => __( 'Flip', $td ) ),
  array( 'value' => 'flipInX',           'label' => __( 'Flip In X', $td ) ),
  array( 'value' => 'flipInY',           'label' => __( 'Flip In Y', $td ) ),
  array( 'value' => 'fadeIn',            'label' => __( 'Fade In', $td ) ),
  array( 'value' => 'fadeInUp',          'label' => __( 'Fade In Up', $td ) ),
  array( 'value' => 'fadeInDown',        'label' => __( 'Fade In Down', $td ) ),
  array( 'value' => 'fadeInLeft',        'label' => __( 'Fade In Left', $td ) ),
  array( 'value' => 'fadeInRight',       'label' => __( 'Fade In Right', $td ) ),
  array( 'value' => 'bounceIn',          'label' => __( 'Bounce In', $td ) ),
  array( 'value' => 'bounceInUp',        'label' => __( 'Bounce In Up', $td ) ),
  array( 'value' => 'bounceInDown',      'label' => __( 'Bounce In Down', $td ) ),
  array( 'value' => 'bounceInLeft',      'label' => __( 'Bounce In Left', $td ) ),
  array( 'value' => 'bounceInRight',     'label' => __( 'Bounce In Right', $td ) ),
  array( 'value' => 'rotateIn',          'label' => __( 'Rotate In', $td ) ),
  array( 'value' => 'rotateInUpLeft',    'label' => __( 'Rotate In Up Left', $td ) ),
  array( 'value' => 'rotateInUpRight',   'label' => __( 'Rotate In Up Right', $td ) ),
  array( 'value' => 'rotateInDownLeft',  'label' => __( 'Rotate In Down Left', $td ) ),
  array( 'value' => 'rotateInDownRight', 'label' => __( 'Rotate In Down Right', $td ) ),
  array( 'value' => 'zoomIn',            'label' => __( 'Zoom In', $td ) ),
  array( 'value' => 'zoomInUp',          'label' => __( 'Zoom In Up', $td ) ),
  array( 'value' => 'zoomInDown',        'label' => __( 'Zoom In Down', $td ) ),
  array( 'value' => 'zoomInLeft',        'label' => __( 'Zoom In Left', $td ) ),
  array( 'value' => 'zoomInRight',       'label' => __( 'Zoom In Right', $td ) )
);