<?php return array (
  'title' => 'Use the Force',
  'elements' =>
  array (
    0 =>
    array (
      'elType' => 'section',
      'title' => 'Use the Force',
      'elements' =>
      array (
        0 =>
        array (
          'title' => 'Row 1',
          'elType' => 'row',
          'columnLayout' => '1/1',

          'elements' =>
          array (
            0 =>
            array (
              'active' => true,
              'elType' => 'column',
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'elements' =>
              array (
                0 =>
                array (
                  'elType' => 'custom-headline',
                  'content' => 'Choose Your Side',
                  'level' => 'h2',
                  'looks_like' => 'h3',
                  'accent' => true,
                  'type' => 'center',
                  'custom_id' => '',
                  'class' => 'man',
                  'style' => '',
                  'text_align' => 'center-text',
                ),
              ),
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            1 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            2 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            3 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            4 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            5 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
          ),
          'childType' => 'column',
          'inner_container' => true,
          'marginless_columns' => false,
          'margin' =>
          array (
            0 => '0px',
            1 => 'auto',
            2 => '30px',
            3 => 'auto',
            4 => 'unlinked',
          ),
          'padding' =>
          array (
            0 => '0px',
            1 => '0px',
            2 => '0px',
            3 => '0px',
            4 => 'unlinked',
          ),
          'border_style' => 'none',
          'border_color' => '',
          'border' =>
          array (
            0 => '1px',
            1 => '1px',
            2 => '1px',
            3 => '1px',
            4 => 'linked',
          ),
          'text_align' => 'none',
          'visibility' =>
          array (
          ),
          'custom_id' => '',
          'class' => '',
          'style' => '',
          'bg_color' => '',
        ),
        1 =>
        array (
          'elType' => 'row',
          'title' => 'Row 2',
          'columnLayout' => '1/2 + 1/2',

          'elements' =>
          array (
            0 =>
            array (
              'active' => true,
              'elType' => 'column',
              'size' => '1/2',
              'title' => '1/2',
              'childType' => 'any',
              'elements' =>
              array (
                0 =>
                array (
                  'elType' => 'card',
                  'animation' => 'flip-from-top',
                  'center_vertically' => true,
                  'card_padding' =>
                  array (
                    0 => '10%',
                    1 => '10%',
                    2 => '10%',
                    3 => '10%',
                    4 => 'linked',
                  ),
                  'front_title' => 'Rebel Alliance',
                  'front_text' => 'Formed from resistance movements that arose during the Clone Wars, the Rebellion works in secret to overthrow the Emperor and restore democracy.',
                  'front_border_style' => 'solid',
                  'front_border_color' => '#a7300b',
                  'front_border_width' =>
                  array (
                    0 => '8px',
                    1 => '8px',
                    2 => '8px',
                    3 => '8px',
                    4 => 'linked',
                  ),
                  'front_color' => '#ffffff',
                  'front_bg_color' => '#f1592a',
                  'front_graphic' => 'icon',
                  'front_icon' => 'ra',
                  'front_icon_size' => '36px',
                  'front_icon_color' => '#f69374',
                  'front_image' => '',
                  'front_image_width' => '100px',
                  'back_title' => 'The Good Guys',
                  'back_text' => 'Click the button below to begin your journey as a member of the Rebel Alliance.',
                  'back_border_style' => 'solid',
                  'back_border_color' => '#a7300b',
                  'back_border_width' =>
                  array (
                    0 => '8px',
                    1 => '8px',
                    2 => '8px',
                    3 => '8px',
                    4 => 'linked',
                  ),
                  'back_color' => '#ffffff',
                  'back_bg_color' => '#f1592a',
                  'back_button_text' => 'Join the Alliance!',
                  'back_button_link' => '#',
                  'back_button_color' => '#ffffff',
                  'back_button_bg_color' => '#a7300b',
                  'custom_id' => '',
                  'class' => '',
                  'style' => '',
                ),
              ),
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            1 =>
            array (
              'elType' => 'column',
              'active' => true,
              'size' => '1/2',
              'title' => '1/2',
              'childType' => 'any',
              'elements' =>
              array (
                0 =>
                array (
                  'elType' => 'card',
                  'animation' => 'flip-from-top',
                  'center_vertically' => true,
                  'card_padding' =>
                  array (
                    0 => '10%',
                    1 => '10%',
                    2 => '10%',
                    3 => '10%',
                    4 => 'linked',
                  ),
                  'front_title' => 'Galactic Empire',
                  'front_text' => 'The Galactic Empire ruled for years through fear with a mighty military force including stormtroopers and the planet-destroying Death Star.',
                  'front_border_style' => 'solid',
                  'front_border_color' => '#222222',
                  'front_border_width' =>
                  array (
                    0 => '8px',
                    1 => '8px',
                    2 => '8px',
                    3 => '8px',
                    4 => 'linked',
                  ),
                  'front_color' => '#ffffff',
                  'front_bg_color' => '#3d3d3d',
                  'front_graphic' => 'icon',
                  'front_icon' => 'ge',
                  'front_icon_size' => '36px',
                  'front_icon_color' => '#898989',
                  'front_image' => '',
                  'front_image_width' => '100px',
                  'back_title' => 'The Bad Guys',
                  'back_text' => 'Click the button below to begin your journey as a member of the Galactic Empire.',
                  'back_border_style' => 'solid',
                  'back_border_color' => '#222222',
                  'back_border_width' =>
                  array (
                    0 => '8px',
                    1 => '8px',
                    2 => '8px',
                    3 => '8px',
                    4 => 'linked',
                  ),
                  'back_color' => '#ffffff',
                  'back_bg_color' => '#3d3d3d',
                  'back_button_text' => 'Join the Empire!',
                  'back_button_link' => '#',
                  'back_button_color' => '#ffffff',
                  'back_button_bg_color' => '#222222',
                  'custom_id' => '',
                  'class' => '',
                  'style' => '',
                ),
              ),
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            2 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/3',
              'title' => '1/3',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            3 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            4 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
            5 =>
            array (
              'elType' => 'column',
              'active' => false,
              'size' => '1/1',
              'title' => '1/1',
              'childType' => 'any',
              'element_info' => false,
              'fade' => false,
              'fade_animation' => 'in',
              'fade_animation_offset' => '45px',
              'text_align' => 'none',
              'custom_id' => '',
              'class' => '',
              'style' => '',
              'bg_color' => '',
              'padding' =>
              array (
                0 => '0px',
                1 => '0px',
                2 => '0px',
                3 => '0px',
                4 => 'linked',
              ),
              'border_style' => 'none',
              'border_color' => '',
              'border' =>
              array (
                0 => '1px',
                1 => '1px',
                2 => '1px',
                3 => '1px',
                4 => 'linked',
              ),
            ),
          ),
          'childType' => 'column',
          'inner_container' => true,
          'marginless_columns' => false,
          'margin' =>
          array (
            0 => '0px',
            1 => 'auto',
            2 => '0px',
            3 => 'auto',
            4 => 'unlinked',
          ),
          'padding' =>
          array (
            0 => '0px',
            1 => '0px',
            2 => '0px',
            3 => '0px',
            4 => 'unlinked',
          ),
          'border_style' => 'none',
          'border_color' => '',
          'border' =>
          array (
            0 => '1px',
            1 => '1px',
            2 => '1px',
            3 => '1px',
            4 => 'linked',
          ),
          'text_align' => 'none',
          'visibility' =>
          array (
          ),
          'custom_id' => '',
          'class' => '',
          'style' => '',
          'bg_color' => '',
        ),
      ),
      'childType' => 'row',
      'bg_type' => 'color',
      'bg_color' => '#ffffff',
      'bg_image' => '',
      'bg_pattern_toggle' => false,
      'parallax' => false,
      'bg_video' => '',
      'bg_video_poster' => '',
      'margin' =>
      array (
        0 => '0px',
        1 => '0px',
        2 => '0px',
        3 => '0px',
        4 => 'unlinked',
      ),
      'padding' =>
      array (
        0 => '45px',
        1 => '0px',
        2 => '45px',
        3 => '0px',
        4 => 'unlinked',
      ),
      'border_style' => 'none',
      'border_color' => '',
      'border' =>
      array (
        0 => '1px',
        1 => '1px',
        2 => '1px',
        3 => '1px',
        4 => 'linked',
      ),
      'text_align' => 'none',
      'visibility' =>
      array (
      ),
      'custom_id' => '',
      'class' => '',
      'style' => '',
    ),
  ),
);